PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX pav: <http://purl.org/pav/>

CONSTRUCT {
  ?class rdf:type owl:Class ;
         rdfs:label ?label .
}
WHERE {
  ?class rdf:type owl:Class .

  OPTIONAL { ?class rdfs:label ?label }

  FILTER NOT EXISTS { ?class oboInOwl:creation_date ?creationDate }

  FILTER NOT EXISTS { ?class pav:lastUpdateOn ?lastUpdateOn }

  FILTER (STRSTARTS(STR(?class), "http://purl.obolibrary.org/obo/digitrubber/digitrubber-full.owl/DIGITRUBBER_") || STRSTARTS(STR(?class), "https://www.tib.eu/digitrubber#DIGITRUBBER_"))
}
