PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pav:  <http://purl.org/pav/>

SELECT ?class ?label
WHERE {
  ?class rdf:type owl:Class .
  FILTER ( isIRI(?class) )

  OPTIONAL { ?class rdfs:label ?label }

  FILTER NOT EXISTS {
    ?class pav:lastUpdateOn ?lastUpdate .
  }

  # Exclude imported foundational ontologies
 FILTER (!STRSTARTS(STR(?class), "http://purl.obolibrary.org/obo/BFO_") && !STRSTARTS(STR(?class), "http://purl.obolibrary.org/obo/IAO_") && !STRSTARTS(STR(?class), "https://w3id.org/pmd/co/PMD_"))

}
ORDER BY ?class
